{% set version = "0.3.2" %}

package:
  name: blobtk
  version: {{ version }}

build:
  number: 0

source:
  git_url: https://github.com/blobtoolkit/blobtk.git
  git_rev: {{ version }}
  # git_depth: 1
  # url: https://github.com/blobtoolkit/blobtk/archive/{{ version }}.tar.gz
  # sha256: 1d62bce3232ab6afc8ab07c53c559d8d991657f917ddd00e3dbe6938bc881fa1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - rust >=1.52
    - pkg-config
    #- python {{ python }}
  host:
    - openssl
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    

test:
  commands:
    - blobtk --help
    - blobtk --version
    - blobtk depth --help
    - blobtk filter --help


  imports:
    - blobtk

about:
  home: https://github.com/blobtoolkit/blobtk
  license: MIT
  license_file: LICENSE
  summary: |
    Core utilities for BlobToolKit.
  description: |
    A collection of general purpose command line tools optimised for use cases encoutered in analyses for BlobToolKit.
    Includes tools for FASTA/FASTQ filtering and sequencing coverage depth calculation.
