es:
  host: "http://localhost"
  port: 9200
  hub:
    name: goat
    release: 2021.10.15
    taxonomy: ncbi
assembly:
  accession: &ACCESSION GCA_016920705.1
sequence_report:
  accession: *ACCESSION
  local_path: "~/tmp/{ACCESSION}.sequence_report.jsonl"
bed:
  accession: *ACCESSION
  lines_per_unit: 1000
  windows:
    - type: size
      size: 1000000
      remnant_policy: Centered
    # - type: size
    #   size: 100000
    #   remnant_policy: Centered
    - type: proportion
      proportion: 0.1
  files:
    - path: "https://gap.cog.sanger.ac.uk/{ACCESSION}/base_content/k1/{ACCESSION}.GC.1k.bedGraph.gz"
      local_path: "~/tmp/{ACCESSION}.GC.1k.bedGraph.gz"
      value_columns:
        - label: gc
          index: 3
          type: float
          summary_functions: &SUMMARY_FUNCTIONS
            - name: mean
            - name: subwindow_variance
              value:
                size: 100
          normalisation:
            method: zscore
            statistic: mean_std
            scope: assembly
    - path: "https://gap.cog.sanger.ac.uk/{ACCESSION}/base_content/k1/{ACCESSION}.N.1k.bedGraph.gz"
      local_path: "~/tmp/{ACCESSION}.N.1k.bedGraph.gz"
      value_columns:
        - label: n
          index: 3
          type: float
          summary_functions: *SUMMARY_FUNCTIONS
busco:
  accession: *ACCESSION
  tables:
    - path: "https://gap.cog.sanger.ac.uk/{ACCESSION}/busco/{LINEAGE}/{ACCESSION}.{LINEAGE}.full_table.tsv.gz"
      local_path: "~/tmp/{ACCESSION}.{LINEAGE}.full_table.tsv.gz"
      lineages: &LINEAGES
        - anopheles_odb12
        - arthropoda_odb10
        - arthropoda_odb12
        - diptera_odb12
  algs:
    - name: diptera_alg
      lineage: diptera_odb12
      path: https://raw.githubusercontent.com/Obscuromics/diptera-ALGs/refs/heads/main/tables/ALGs_syngraph_diptera.tsv
      local_path: "~/tmp/diptera_alg.tsv"
    - name: brachycera_alg
      lineage: diptera_odb12
      path: https://raw.githubusercontent.com/Obscuromics/diptera-ALGs/63446cba275a760af2a15750504927878e2f25a5/tables/ALGs_syngraph_brachycera.tsv
      local_path: "~/tmp/brachycera_alg.tsv"
import:
  entity_types:
    - sequence
    - window
    - busco
    - attribute
  busco_tallies:
    lineages: *LINEAGES
    assembly_counts_output: "./busco_assembly_counts.tsv"
  synteny_index:
    enrich_busco_features: true
    index_synteny_loci: true
    index_synteny_blocks: true
