es:
  host: "http://localhost"
  port: 9200
  hub:
    name: goat
    release: 2021.10.15
    taxonomy: ncbi

assembly:
  accession: GCA_016920705.1
  taxon_id: 7157

sequence:
  report:
    # path: "https://example.org/{ACCESSION}/sequence_report.jsonl"
    local_path: "~/tmp/{ACCESSION}.sequence_report.jsonl"
  metadata:
    # telomere:
    #   source:
    #     path: "https://example.org/{ACCESSION}/telomere_repeats.bed.gz"
    #     local_path: "~/tmp/{ACCESSION}.telomere_repeats.bed.gz"
    #   assign_to: [sequence]
    #   fields:
    #     telomere_state: start|end|both|none
    #     has_internal_telomeres: bool
    # centromere:
    #   source:
    #     path: "https://example.org/{ACCESSION}/centromere.bed.gz"
    #     local_path: "~/tmp/{ACCESSION}.centromere.bed.gz"
    #   assign_to: [sequence]
    #   fields:
    #     centromere_presence: present|absent
    #     centromere_pattern: mono|multi|holo
    #     centromere_count: integer

annotations:
  busco:
    source:
      path: "https://gap.cog.sanger.ac.uk/{ACCESSION}/busco/{LINEAGE}/{ACCESSION}.{LINEAGE}.full_table.tsv.gz"
      local_path: "~/tmp/{ACCESSION}.{LINEAGE}.full_table.tsv.gz"
    assign_to: [feature]
    fields: {}
    algs:
      - name: diptera_alg
        lineage: diptera_odb12
        path: "https://raw.githubusercontent.com/Obscuromics/diptera-ALGs/refs/heads/main/tables/ALGs_syngraph_diptera.tsv"
        local_path: "~/tmp/diptera_alg.tsv"
        # primary alg used for BUSCO feature enrichment and synteny-block generation
      - name: brachycera_alg
        lineage: diptera_odb12
        path: "https://raw.githubusercontent.com/Obscuromics/diptera-ALGs/63446cba275a760af2a15750504927878e2f25a5/tables/ALGs_syngraph_brachycera.tsv"
        local_path: "~/tmp/brachycera_alg.tsv"
  # repeats:
  #   source:
  #     path: "https://example.org/{ACCESSION}/repeats.bed.gz"
  #     local_path: "~/tmp/{ACCESSION}.repeats.bed.gz"
  #   assign_to: [sequence, window]
  #   fields:
  #     repeat_density: float

windowing:
  lines_per_unit: 1000
  windows:
    - type: size
      size: 1000000
      remnant_policy: Centered
    - type: proportion
      proportion: 0.1
  files:
    - path: "https://gap.cog.sanger.ac.uk/{ACCESSION}/base_content/k1/{ACCESSION}.GC.1k.bedGraph.gz"
      local_path: "~/tmp/{ACCESSION}.GC.1k.bedGraph.gz"
      value_columns:
        - label: gc
          index: 3
          type: float
          summary_functions:
            - name: mean
          normalisation:
            method: zscore
            statistic: mean_std
            scope: assembly
    - path: "https://gap.cog.sanger.ac.uk/{ACCESSION}/base_content/k1/{ACCESSION}.N.1k.bedGraph.gz"
      local_path: "~/tmp/{ACCESSION}.N.1k.bedGraph.gz"
      value_columns:
        - label: n
          index: 3
          type: float
          summary_functions:
            - name: mean
          normalisation:
            method: zscore
            statistic: mean_std
            scope: assembly

# derived_metrics:
#   - name: distance_to_telomere
#     target: window
#     source: sequence
#     anchor: midpoint
#     output_type: float
#   - name: window_flags
#     target: window
#     source: sequence
#     flags:
#       - nearest_telomere_valid
#       - has_internal_telomeres
#       - has_telomere_start
#       - has_telomere_end

import:
  entity_types:
    - sequence
    - window
    - busco
    - attribute
  busco_tallies:
    lineages:
      - diptera_odb12
    assembly_counts_output: "./busco_assembly_counts.tsv"
  synteny_index:
    enrich_busco_features: true
    index_synteny_loci: true
    index_synteny_blocks: true
