name: conda release

on:
  push:

jobs:
  fetch-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: fetch wheels
        run: |
          mkdir -p ./dist
          cd ./dist
          curl -L https://pypi.python.org/pypi/blobtk/json | jq -r '.releases["0.2.4"] | map(.url) | map(select(test("10_7") | not)) | .[]' | while read URL; do wget $URL; done
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist

  create-conda-release-macos:
    name: Create conda release Mac
    runs-on: macos-latest
    #if: "startsWith(github.ref, 'refs/tags/')"
    needs: fetch-wheels
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: ./dist
      - name: copy files
        run: |
          mkdir -p ./conda/dist
          cp ./dist/*macos*.whl ./conda/dist/
      - name: conda build
        run: |
          conda install -y conda-build
          conda config --set anaconda_upload yes
          ANACONDA_API_TOKEN=${{ secrets.ANACONDA_API_TOKEN }}
          conda build ./conda

  create-conda-release-linux:
    name: Create conda release Linux
    runs-on: ubuntu-latest
    #if: "startsWith(github.ref, 'refs/tags/')"
    needs: fetch-wheels
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: ./dist
      - name: Install libssl-dev
        run: sudo apt-get install -y libssl-dev
      - name: copy files
        run: |
          mkdir -p ./conda/dist
          cp ./dist/*linux*.whl ./conda/dist/
      - name: conda build
        run: |
          conda install -y conda-build
          conda config --set anaconda_upload yes
          ANACONDA_API_TOKEN=${{ secrets.ANACONDA_API_TOKEN }}
          conda build ./conda
