name: release-core

on:
  push:
    tags:
      - "*"

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - name: Build
        working-directory: ./rust
        run: cargo build --release
      - name: Tests
        working-directory: ./rust
        run: cargo test --no-default-features --release
      - name: Build wheels - x86_64
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          args: -i python --release --out dist --sdist -m rust/Cargo.toml
      - name: Install built wheel - x86_64
        run: |
          pip install blobtoolkit-core --no-index --find-links ./dist --force-reinstall
      - name: Build wheels - universal2
        if: ${{ matrix.python-version >= '3.8' || contains(fromJson('["3.10", "3.11"]'), matrix.python-version) }}
        uses: PyO3/maturin-action@v1
        with:
          args: -i python --release --universal2 --out dist -m rust/Cargo.toml
      - name: Install built wheel - universal2
        if: ${{ matrix.python-version >= '3.8' || contains(fromJson('["3.10", "3.11"]'), matrix.python-version) }}
        run: |
          pip install blobtoolkit-core --no-index --find-links ./dist --force-reinstall
      # - name: Python UnitTest
      #   run: |
      #     pip install -r dev-requirements.txt
      #     make test
      - name: Rename binary
        run: |
          mv ./rust/target/release/blobtoolkit-core ./rust/target/release/blobtoolkit-core-macos
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: rust/target/release/blobtoolkit-core-macos
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist

  # windows:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
  #       target: [x64, x86]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         architecture: ${{ matrix.target }}
  #     - name: Install Rust toolchain
  #       uses: dtolnay/rust-toolchain@stable
  #     - name: Build
  #       if: matrix.target == 'x64'
  #       run: cargo build --release
  #     - name: Tests
  #       if: matrix.target == 'x64'
  #       run: cargo test --no-default-features --release
  #     - name: Build wheels
  #       uses: PyO3/maturin-action@v1
  #       with:
  #         target: ${{ matrix.target }}
  #         args: -i python --release --out dist
  #     - name: Install built wheel
  #       run: |
  #         pip install cramjam --no-index --find-links dist --force-reinstall
  #     - name: Python UnitTest
  #       run: |
  #         pip install -r dev-requirements.txt
  #         make test
  #     - name: Upload wheels
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: wheels
  #         path: dist

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        target: [x86_64]
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        working-directory: ./rust
        run: cargo build --release
      - name: Tests
        working-directory: ./rust
        run: cargo test --no-default-features --release
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Audit
        working-directory: ./rust
        run: cargo install cargo-audit && cargo audit
      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          args: -i ${{ matrix.python-version }} --release --out dist -m rust/Cargo.toml
      - name: Python UnitTest
        if: matrix.target == 'x86_64'
        run: |
          pip install blobtoolkit-core --no-index --find-links ./dist --force-reinstall
      #     pip install -r dev-requirements.txt
      #     make test
      # - name: Test no numpy installed works
      #   if: matrix.target == 'x86_64'
      #   run: |
      #     pip uninstall numpy -y
      #     python -m pytest tests/test_no_numpy.py
      - name: Rename binary
        run: |
          mv ./rust/target/release/blobtoolkit-core ./rust/target/release/blobtoolkit-core-linux
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: rust/target/release/blobtoolkit-core-linux
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist

  create-github-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs:
      - macos
      - linux
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ./dist
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: ./dist
      - name: create release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          title: "v${{github.ref_name}}"
          files: |
            dist/blobtoolkit-core-macos
            dist/blobtoolkit-core-linux
            dist/blobtoolkit-core*.tgz

  upload-to-pypi:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [macos, linux]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing *
